### PR TITLE
style readme

### PR DESCRIPTION
**Pull request by brenovambaster**
## Just small details. Please look at the changes I've made and if you like it, accept the PR. I think the readme has become more readable.
 To see the changes, you can go to my repository. [https://github.com/brenovambaster/Hacktoberfest-2021](https://github.com/brenovambaster/Hacktoberfest-2021)

### CODE REVIEW

**Comment by Shubhamrawat5** [comment]
Is there also for number of pull request, if so then can you also add for pr

**Comment by brenovambaster** [comment]
okay. I will do this.

**Comment by brenovambaster** [comment]
Allright.

**Comment by Shubhamrawat5** [comment]
Great!!

**Pull request merged**
