### PR TITLE
Added Brian Kernighan Algorithm

### PR DESCRIPTION
**Pull request by debanjan-2002**
Hello Respected Sir,
I have added a well written and structured code for "Brian Kernighan's Algorithm". If you feel like it is worth it, then please merge it with the Hactoberfest tag. If any changes are required then please inform me.

Regards,
Debanjan Poddar
@Shubhamrawat5

### CODE REVIEW

**Review by brenovambaster — APPROVED** [review]

**Comment by debanjan-2002** [comment]
Kindly merge this with the hacktoberfest tag, if it is okay.

Regards,
Debanjan Poddar
@brenovambaster 
@Shubhamrawat5

**Comment by Shubhamrawat5** [comment]
@brenovambaster  how are you adding yourself as reviewers?

**Comment by debanjan-2002** [comment]
Sir,
I don't know who is @brenovambaster .
Please merge it, if the code is good enough.
@Shubhamrawat5

**Comment by brenovambaster** [comment]
Sir, @Shubhamrawat5, @debanjan-2002
I don't have the power to merge, I just review the code and give the opinion. Who can merge is just the repository owner.

**Comment by Shubhamrawat5** [comment]
Yeah. Got it now

**Comment by brenovambaster** [comment]
@Shubhamrawat5 
> @brenovambaster how are you adding yourself as reviewers?

Anyone can review third-party code, but cannot merge it. Unless the repository owner gives you this authorization. In this case, I just reviewed it.

**Pull request merged**
